apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-prometheus
  template:
    metadata:
      labels:
        app: fcg-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.54.1
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: fcg-prometheus-config
