apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-postgres-init-script

data:
  init.sql: |
    CREATE DATABASE fcg_users;
    CREATE DATABASE fcg_catalog;
    CREATE DATABASE fcg_payments;
    CREATE DATABASE konga;