apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-rabbitmq
  template:
    metadata:
      labels:
        app: fcg-rabbitmq
    spec:
      containers:
        - name: fcg-rabbitmq
          image: rabbitmq:4-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: fcg-rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: fcg-rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json
      volumes:
        - name: rabbitmq-config
          configMap:
            name: fcg-rabbitmq-config
