apiVersion: v1
kind: Service
metadata:
  name: fcg-rabbitmq
  labels:
    app: fcg-rabbitmq
spec:
  # LoadBalancer para a Azure Function (fora do cluster) alcançar o AMQP.
  # ATENÇÃO: exposição pública só para demo do TC — apague o RG depois.
  type: LoadBalancer
  selector:
    app: fcg-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
