apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-kong-config
data:
  kong.yml: |
    _format_version: "3.0"

    consumers:
      - username: fcg-client
        jwt_secrets:
          - key: FCG.Users.API
            algorithm: HS256
            secret: "rN8#kL2vQ9@xT5mP1!zC7$dH4^bW6&yU"

    services:
      - name: users-api
        url: http://fcg-users-api:80
        routes:
          - name: users-route
            paths:
              - /users
            strip_path: true

      - name: catalog-api
        url: http://fcg-catalog-api:80
        routes:
          - name: catalog-health
            paths:
              - /catalog/health
            strip_path: false
            plugins:
              - name: request-transformer
                config:
                  replace:
                    uri: /health
          - name: catalog-metrics
            paths:
              - /catalog/metrics
            strip_path: false
            plugins:
              - name: request-transformer
                config:
                  replace:
                    uri: /metrics
          - name: catalog-route
            paths:
              - /catalog
            strip_path: true
            plugins:
              - name: jwt
                config:
                  key_claim_name: iss
                  claims_to_verify:
                    - exp
