apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-opensearch
  template:
    metadata:
      labels:
        app: fcg-opensearch
    spec:
      containers:
        - name: fcg-opensearch
          image: opensearchproject/opensearch:2.17.1
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: bootstrap.memory_lock
              value: "false"
            - name: OPENSEARCH_JAVA_OPTS
              # Heap reduzido para caber em AKS 1 node (D2s_v4 / ~8 GB)
              value: -Xms256m -Xmx256m
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: "1"
          volumeMounts:
            - name: fcg-opensearch-data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: fcg-opensearch-data
          emptyDir: {}
